[package]
name = "irondb"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/malawarecreator/irondb"
authors = ["benjamin liu"]
license = "MIT"
description = "Key-value storage engine"

[dependencies]
